/** HERE YOU DEFINE THE RELATIVE ENDPOINTS OF BACKEND APP */
/** INITIAL PATH OF BACKEND APP SHOULD BE DEFINED IN .ENV */

export const SOMETHING = '/something';
export const PRINT_SOMETHING = `${SOMETHING}/printPDF`;
export const ANYTHING = '/anything';

/** NOTE: FOR PATH THAT NEEDS TU PASS PARAMETERS, YOU SHOULD DEFINE
 * MANUALLY USING TEMPLATE STRINGS. e.g (`/something/${id}`)
 */