const historyContinua = [
    {
        categoria:'Productividad',
        nivel:'Buena',
        fechaRegistro:'22/04/2023',
        detalle:'',
    },
        {
        categoria:'Productividad',
        nivel:'Buena',
        fechaRegistro:'22/04/2023',
        detalle:'',
    },
        {
        categoria:'Productividad',
        nivel:'Buena',
        fechaRegistro:'22/04/2023',
        detalle:'',
    },
        {
        categoria:'Productividad',
        nivel:'Buena',
        fechaRegistro:'22/04/2023',
        detalle:'',
    },
        {
        categoria:'Productividad',
        nivel:'Buena',
        fechaRegistro:'22/04/2023',
        detalle:'',
    },
        {
        categoria:'Productividad',
        nivel:'Buena',
        fechaRegistro:'22/04/2023',
        detalle:'',
    },
        {
        categoria:'Productividad',
        nivel:'Buena',
        fechaRegistro:'22/04/2023',
        detalle:'',
    },
        {
        categoria:'Productividad',
        nivel:'Buena',
        fechaRegistro:'22/04/2023',
        detalle:'',
    },

]

export default historyContinua;